### ISSUE TITLE
crashes with no message

### ISSUE THREAD

**Issue by CZTeo** [dreamnettech/dreampower#125] opened 2021-12-31 22:06 UTC
after opening dreampower exe the terminal shows up for a brief second then closes.How do i use this program?

**Comment by WeLoveGaming** [comment] 2022-01-21 04:40
I am getting this issue as well

**Comment by Pingasmaster** [comment] 2022-02-12 11:51
...
This is not a bug.
It is because dreampower.exe is not a software with a graphical interface, so when you open it by just double-clicking on it, it does nothing. Because you have not provided any arguments to it.
In order to make it work, open the terminal (serach for cmd, click Oen as admin) and type
cd Thedirectory
where you replace Thedirectory by the directory where dreampower is located, for example C:\User\username\Downloads\dreampower\
then, type
dreampower.exe --help
and it will give you the arguments that you have to or can give him.
If you wish to use something with a graphical interface, just go to https://www.dreamtime.tech/docs/installation and follow procedure.
Please reply or close the issue, thanks.

**Comment by CZTeo** [comment] 2022-02-12 13:00
> ...
> This is not a bug.
> It is because dreampower.exe is not a software with a graphical interface, so when you open it by just double-clicking on it, it does nothing. Because you have not provided any arguments to it.
> In order to make it work, open the terminal (serach for cmd, click Oen as admin) and type
> cd Thedirectory
> where you replace Thedirectory by the directory where dreampower is located, for example C:\User\username\Downloads\dreampower\
> then, type
> dreampower.exe --help
> and it will give you the arguments that you have to or can give him.
> If you wish to use something with a graphical interface, just go to https://www.dreamtime.tech/docs/installation and follow procedure.
> Please reply or close the issue, thanks.

Gotcha,thx for helping a noobie out

**Closed** 2022-02-12 13:01 UTC
Labels: bug
